version: 2.1

orbs:
  gcp-gcr: bahnx/gcp-gcr@1.1.0
  gcp-gke: bahnx/gcp-gke@1.2.0

jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - setup_remote_docker
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run:
          name: Setup Private GitHub Repo Access
          command: git config --global "url.https://${GITHUB_TOKEN}:@github.com.insteadOf" 'ssh://git@github.com'
      - run:
          name: Setup Private NPM Registry Access
          command: |
            npm config set //$NPM_REGISTRY/:_authToken $NPM_TOKEN
            npm config set //$NPM_REGISTRY/:always-auth true
            npm config set @bahn-x:registry https://$NPM_REGISTRY
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint Code
          command: yarn lint
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Static Site
          command: yarn build:docs
      - gcp-gcr/build-push-docker:
          image: "dbx-web"

  deploy:
    docker:
      - image: eu.gcr.io/$GCLOUD_PROJECT_ID/gcloud-build:SDK-255.0.0
        auth:
          username: _json_key
          password: $GCR_KEY
    steps:
      - checkout
      - gcp-gke/deploy-to-kubernetes:
          k8s-namespace: $STAGE

workflows:
  version: 2

  dbx-web-production-workflow:
    jobs:
      - build:
          context: gcloud-webproducts-prod
      - deploy:
          context: gcloud-webproducts-prod
          requires:
            - build
          filters:
            branches:
              only:
                - master
