apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbx-web
  labels:
    app: dbx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbx-web
  template:
    metadata:
      labels:
        app: dbx-web
    spec:
      containers:
      - name: dbx-web
        image: eu.gcr.io/web-products-production/dbx-web:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "dbx-web"}'
  name: dbx-web-service
spec:
  type: NodePort
  selector:
    app: dbx-web
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: dbx-web
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: dbx-web

