secrets:
    auth: ENC[AES256_GCM,data:37KirtZSX7ww8oS28eoAVgkyr7MAGQO0BPxkjV+6POTS7b/TTDQE1moiYEYgW47omRKAYkzevhE=,iv:pjOJnO3Ys4k1GtJNUGq19gQpdhlZimGoqVphUmdZouI=,tag:XlyifTuL5Z81b2zKb1dJdQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/bahnx-staging/locations/global/keyRings/kubesec/cryptoKeys/team-platform
        created_at: '2020-07-08T13:52:09Z'
        enc: CiQA3NiyvwC1TLR5o3YHYMdt3067daKgfyunlMAOPOeSnP3Z5VISSQARLKbRswUb9aqSCq8QpJTKYxEzibvBZP9iGG3J39BD53vKuDtOF6A3s7vlZ3+dN62K/fsVeQmJGtMn1hFL7+MxVHd9zkP63wI=
    azure_kv: []
    lastmodified: '2020-12-02T13:53:00Z'
    mac: ENC[AES256_GCM,data:mMKp/ozCzDjGHcoWSwHtMf+4EH5Oq6VWUMcE+DA/F4ycdDrhc6vrvbZSKIlXSyuYXS//EgCN+Q48KxBlXxFbhcLFoa5xom+/3t6WIlAHMgmou+ZlIR9ucqXKl8YyG3yJuXDL9od5rzfCpZlFUc1ICOSjS+/XnV1ytoWScpbK28w=,iv:XHOdjjcfWjDOX4ZCbR3zVrLjaA7nycDd6KgqnnMUkWk=,tag:NswzUGZINWef1xYWxO83OQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
