---
helmDefaults:
  tillerless: true

repositories:
  - name: bahnx
    url: https://bahn-x.github.io/helm/

releases:
  - name: dbx-web
    chart: bahnx/service
    version: 1.0.1
    values:
      - values.yaml.gotmpl
      - image:
          repository: {{ requiredEnv "DOCKER_REGISTRY" }}/{{ requiredEnv "STAGE" }}/web/dbx-web
          tag: {{ requiredEnv "CIRCLE_SHA1" | quote }}
        service:
          port: 8080
        readinessProbe:
          path: /
        ingress:
          enabled: true
          annotations:
            {{ if eq .Environment.Name "prod" }}
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/auth-type: basic
            # name of the secret that contains the user/password definitions
            nginx.ingress.kubernetes.io/auth-secret: dbx-web-service
            # message to display with an appropriate context why the authentication is required
            nginx.ingress.kubernetes.io/auth-realm: 'DPP'                 
            {{ else }}
            kubernetes.io/ingress.class: nginx-private
            {{ end }}
            # https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
            # http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types
            nginx.org/server-snippets: |
              gzip on;
              gzip_comp_level 5;
              gzip_min_length 256;
              gzip_proxied any;
              gzip_types
                application/javascript
                application/json
                image/svg+xml
                text/css
                text/html
                text/javascript;
              gzip_vary on;
          hosts:
            - {{ .Values.host }}
          path: /
          {{ if eq .Environment.Name "prod" }}
          tls:
            - secretName: {{ .Values.host }}
              hosts:
                - {{ .Values.host }}
          {{ end }}


environments:
  dev:
    values:
      - host: dppc.app.bahnx-dev.comp.db.de
  prod:
    values:
      - host: dppc.bahn-x.de
    secrets:
      - prod/secrets.yaml          
